version: "3"

tasks:
  run:
    cmds:
      - python3 -m uvicorn src.main:app --reload

  create_buildx:
    cmds:
      - docker buildx create --name multiarch --use

  build:
    cmds:
      - docker buildx inspect --bootstrap
      - docker buildx build --platform linux/amd64,linux/arm64 --push -t hestm/interview-service:latest .
