from datetime import timedelta
from src.usecases.interfaces.vacancy_service import VacancyServiceBase
from src.domain.vacancy.vacancy import VacancyInfo
from uuid import UUID
from src.domain.room.room import Room


class MockVacancyService(VacancyServiceBase):
    """
    Mock vacancy service
    """

    async def get_vacancy(self, vacancy_id: UUID) -> VacancyInfo:
        return VacancyInfo(
            profession="Python разработчик / Data Scientist",
            position="Junior Python Developer",
            requirements="Pandas, Numpy, Tensorflow, PyTorch, SQLAlchemy",
            questions="",
            tasks=[],
            task_ides=[],
            interview_plan="",  # Will be generated by create_chat
            duration=timedelta(minutes=90),
        )

    async def add_interview_results(self, room: Room) -> None: ...
